[workspace]
resolver = "2"
members = [
    "crates/bsp-core",
    "crates/bsp-ipc",
    "crates/bsp-hotkeys",
    "crates/bsp-compositor",
    "crates/bspc-rs",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
repository = "https://github.com/vitdevelop/bspwm-rs"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
