[package]
name = "bsp-ipc"
description = "bspwm-compatible control socket protocol."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bsp-core = { path = "../bsp-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
